// <auto-generated />
namespace IgrEbillsApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedRemittanceStatusToRemittance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedRemittanceStatusToRemittance));
        
        string IMigrationMetadata.Id
        {
            get { return "201707170117511_addedRemittanceStatusToRemittance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
