//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IgrEbillsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class remittance
    {
        public string remittance_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string remittance_status { get; set; }
        public string MDA_ID { get; set; }
        public Nullable<System.DateTime> remtted_date { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual mda mda { get; set; }
    }
}
