//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IgrEbillsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reportslisting
    {
        public string listing_ID { get; set; }
        public string MenuName { get; set; }
        public string ReportServerURL { get; set; }
        public string MenuUrl { get; set; }
        public string ParentID { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
