//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IgrEbillsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class revenuehead
    {
        public string ID { get; set; }
        public string RevenueCode { get; set; }
        public string Biller_ID { get; set; }
        public string MDA_ID { get; set; }
        public string RevenueName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Taxable { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
